### ISSUE TITLE
Remove “Beta = true” from AltStore source because betas are only available for AltStore Patreon.

### ISSUE THREAD

**Issue by jawshoeadan** [yattee/repos#1]
Basically, there is a bug in AltStore that prevents non-patrons for Riley Testut from being able to download the beta version of the app. Instead, change the app name to something like “Yattee (Beta)” and remove the “beta: true” from the source to fix the issue

**Comment by arekf** [comment]
@jawshoeadan I think it should be ok now, let me know otherwise.
