### ISSUE TITLE
Change build version so new builds show up as updates.

### ISSUE THREAD

**Issue by jawshoeadan** [yattee/repos#2]
Each version currently has a version of 1.2 or 1.3, but when a new build with this release is uploaded, it doesn’t show up as an update in AltStore. Instead, make it something like “1.2b11” or 1.2.11

**Comment by arekf** [comment]
@jawshoeadan I've tried with version `1.3rc` and `1.3.1` and they both show us as update but after updating it still is showing up as pending update. Do you know if this is a bug or me doing something wrong?

**Comment by jawshoeadan** [comment]
It still shows as an update because it’s a mismatch from the CFBundleVersion. You’d have to change that as well
